#!/bin/sh -

DATE=`date +'%Y-%m-%d'`

(echo
 echo Starting new Chado load at: `date`
 echo
 cd $HOME/nightly_load
 (cd $HOME/git/pombase-legacy; git pull) &&
 (cd $HOME/git/pombase-chado; git pull) &&
 date && time bash $HOME/git/pombase-legacy/etc/load-all.sh 'localhost' $DATE kmr44 kmr44 v62 2017-01-30
 date; echo) 2>&1 | tee /var/www/pombase/dumps/builds/load-logs/$DATE.log | tee -a /var/pomcur/logs/nightly_load.log
